Repository aminjonshermatov/mediaViewer, pull requests merged in 2022-07, with the labels that each got.

#1 Db neo4j
  backend/.gitignore
  backend/__pycache__/main.cpython-310.pyc
  backend/config.ini
  backend/main.py
  backend/models/FileNode.py
  backend/parser/__init__.py
  backend/parser/parser.py
  backend/routes/v1.py
  backend/util/__init__.py
  backend/util/config.py
  backend/util/db.py
  backend/util/mime_types.py
  backend/v1/__init__.py
  backend/v1/__pycache__/__init__.cpython-310.pyc
  backend/v1/__pycache__/v1.cpython-310.pyc
  backend/v1/models/__pycache__/FileNode.cpython-310.pyc
  backend/v1/util/__init__.py
  backend/v1/util/__pycache__/__init__.cpython-310.pyc
  backend/v1/util/__pycache__/db.cpython-310.pyc
  backend/v1/util/db.py
  backend/v1/v1.py
Labels: enhancement

#2 sqlite done
  all.sh
  backend.sh
  backend/.env
  backend/.gitignore
  backend/.gitkeep
  backend/__pycache__/main.cpython-310.pyc
  backend/config.ini
  backend/general/config.ini
  backend/main.py
  backend/models/FileNode.py
  backend/parser/__init__.py
  backend/parser/__pycache__/parse.cpython-310.pyc
  backend/parser/data.db
  backend/parser/parse.py
  backend/parser/parser.py
  backend/requirements.txt
  backend/routes/v1.py
  backend/util/__init__.py
  backend/util/__pycache__/db.cpython-310.pyc
  backend/util/__pycache__/mime_types.cpython-310.pyc
  backend/util/config.py
  backend/util/db.py
  backend/util/mime_types.py
  frontend.sh
  parser.sh
Labels: enhancement

#3 Db sqlite
  .gitignore
  all.sh
  backend/__pycache__/main.cpython-310.pyc
  backend/models/__pycache__/FileNode.cpython-310.pyc
  backend/parser/__pycache__/__init__.cpython-310.pyc
  backend/parser/__pycache__/parse.cpython-310.pyc
  backend/parser/data.db
  backend/parser/parse.py
  backend/routes/__pycache__/v1.cpython-310.pyc
  backend/util/__pycache__/__init__.cpython-310.pyc
  backend/util/__pycache__/config.cpython-310.pyc
  backend/util/__pycache__/db.cpython-310.pyc
  backend/util/__pycache__/mime_types.cpython-310.pyc
  backend/util/db.py
  kill.sh
  parser.sh
Labels: bug, enhancement

#4 front partially done
  backend/__pycache__/main.cpython-310.pyc
  backend/main.py
  backend/models/__pycache__/FileNode.cpython-310.pyc
  backend/parser/__pycache__/parse.cpython-310.pyc
  backend/parser/data.db
  backend/routes/__pycache__/v1.cpython-310.pyc
  backend/util/__pycache__/db.cpython-310.pyc
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/app/dto/NodeDto.ts
  frontend/src/app/login/login.component.html
  frontend/src/app/login/login.component.scss
  frontend/src/app/login/login.component.spec.ts
  frontend/src/app/login/login.component.ts
  frontend/src/app/node/models/File.ts
  frontend/src/app/node/models/Folder.ts
  frontend/src/app/node/node.component.html
  frontend/src/app/node/node.component.ts
  frontend/src/app/node/node.service.ts
  frontend/src/app/notification.service.spec.ts
  frontend/src/app/notification.service.ts
  frontend/src/app/register/register.component.html
  frontend/src/app/register/register.component.scss
  frontend/src/app/register/register.component.spec.ts
  frontend/src/app/register/register.component.ts
  frontend/src/environments/environment.prod.ts
  frontend/src/environments/environment.ts
  frontend/src/styles.scss
Labels: enhancement

#5 frontend async pipes & backend cors
  backend/__pycache__/main.cpython-310.pyc
  backend/main.py
  frontend/src/app/node/models/File.ts
  frontend/src/app/node/models/FileType.ts
  frontend/src/app/node/models/Folder.ts
  frontend/src/app/node/node.component.html
  frontend/src/app/node/node.component.ts
  frontend/src/app/node/node.service.ts
  frontend/tsconfig.json
Labels: bug, enhancement

#8 frontend grid list done
  frontend/src/app/app.component.html
  frontend/src/app/app.component.scss
  frontend/src/app/app.module.ts
  frontend/src/app/node/elevation.directive.spec.ts
  frontend/src/app/node/elevation.directive.ts
  frontend/src/app/node/file/file.component.html
  frontend/src/app/node/file/file.component.scss
  frontend/src/app/node/file/file.component.spec.ts
  frontend/src/app/node/file/file.component.ts
  frontend/src/app/node/folder/folder.component.html
  frontend/src/app/node/folder/folder.component.scss
  frontend/src/app/node/folder/folder.component.spec.ts
  frontend/src/app/node/folder/folder.component.ts
  frontend/src/app/node/node.component.html
  frontend/src/app/node/node.component.ts
Labels: enhancement

#9 Added extension
  backend/general/config.ini
  backend/main.py
  backend/parser/data.db
  backend/parser/parse.py
  backend/util/__pycache__/db.cpython-310.pyc
  backend/util/__pycache__/mime_types.cpython-310.pyc
  backend/util/db.py
Labels: bug

#10 Changed add extension
  backend/parser/data.db
  backend/parser/parse.py
  backend/util/__pycache__/mime_types.cpython-310.pyc
  backend/util/mime_types.py
Labels: bug

#11 Sqlite front
  backend/__pycache__/main.cpython-310.pyc
  backend/general/config.ini
  backend/main.py
  backend/parser/__pycache__/parse.cpython-310.pyc
  backend/parser/data.db
  backend/static/3rdpartylicenses.txt
  backend/static/MaterialIcons-Regular.196fa4a92dd6fa73.ttf
  backend/static/MaterialIcons-Regular.1e50f5c2ffa6aba4.eot
  backend/static/MaterialIcons-Regular.7ea2023eeca07427.woff2
  backend/static/MaterialIcons-Regular.db852539204b1a34.woff
  backend/static/assets/fonts/OFL.txt
  backend/static/assets/fonts/Poppins-Black.ttf
  backend/static/assets/fonts/Poppins-BlackItalic.ttf
  backend/static/assets/fonts/Poppins-Bold.ttf
  backend/static/assets/fonts/Poppins-BoldItalic.ttf
  backend/static/assets/fonts/Poppins-ExtraBold.ttf
  backend/static/assets/fonts/Poppins-ExtraBoldItalic.ttf
  backend/static/assets/fonts/Poppins-ExtraLight.ttf
  backend/static/assets/fonts/Poppins-ExtraLightItalic.ttf
  backend/static/assets/fonts/Poppins-Italic.ttf
  backend/static/assets/fonts/Poppins-Light.ttf
  backend/static/assets/fonts/Poppins-LightItalic.ttf
  backend/static/assets/fonts/Poppins-Medium.ttf
  backend/static/assets/fonts/Poppins-MediumItalic.ttf
  backend/static/assets/fonts/Poppins-Regular.ttf
  backend/static/assets/fonts/Poppins-SemiBold.ttf
  backend/static/assets/fonts/Poppins-SemiBoldItalic.ttf
  backend/static/assets/fonts/Poppins-Thin.ttf
  backend/static/assets/fonts/Poppins-ThinItalic.ttf
  backend/static/favicon.ico
  backend/static/index.html
  backend/static/main.7a7a7c73ee82607c.js
  backend/static/main.acbb78e9cfdb4550.js
  backend/static/polyfills.c948a971adecf580.js
  backend/static/runtime.e80a81a64f1f9bc3.js
  backend/static/styles.e96134f196e7a5d4.css
  backend/util/__pycache__/db.cpython-310.pyc
  backend/util/__pycache__/mime_types.cpython-310.pyc
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/node/file/file.component.html
  frontend/src/app/node/file/file.component.ts
  frontend/src/app/node/folder/folder.component.ts
  frontend/src/app/node/gallery-modal/gallery-modal.component.html
  frontend/src/app/node/gallery-modal/gallery-modal.component.scss
  frontend/src/app/node/gallery-modal/gallery-modal.component.spec.ts
  frontend/src/app/node/gallery-modal/gallery-modal.component.ts
  frontend/src/app/node/models/File.ts
  frontend/src/app/node/node.component.html
  frontend/src/app/node/node.component.ts
  frontend/src/app/node/node.service.ts
  frontend/src/environments/environment.prod.ts
  frontend/src/environments/environment.ts
  frontend/src/styles.scss
Labels: enhancement

#12 prod api
  backend/__pycache__/main.cpython-310.pyc
  backend/main.py
  frontend/src/environments/environment.prod.ts
Labels: bug
